### PR TITLE
Make the rebar.config file rebar2-compatible

### PR DESCRIPTION
**Pull request by wk8**
Changed the `rebar.config` to make it backwards-compatible with rebar2.

### CODE REVIEW

**Comment by wk8** [comment]
Sorry, we don't use rebar3 yet...

**Comment by wk8** [comment]
But I suspect we're not the only ones ;-)

**Comment by waisbrot** [comment]
Hi @wk8!  Just a warning that while WHOOP is using this in production right now it's quite a work in progress. I do want to make it good enough for others to use, so I'm very happy to have someone else looking at it. If you find it usable and useful, please let me know and I'll make a tag for you.

For this PR, how about making a rebar.config.script as described in the Rebar3 docs:  [maintaining backwards compatibility while using hex packages](https://www.rebar3.org/docs/from-rebar-2x-to-rebar3#section-maintaining-backwards-compatibility-while-using-hex-packages). That'll allow rebar3 (which is awesome) to do all its bells and whistles and rebar2 will still work.

**Comment by wk8** [comment]
@waisbrot : I've seen it's a WIP still, but it looks much better than the only other Erlang Datadog app I've found, so I'm quite happy using this and contributing to it, thanks for making it available :-) we'll use it in prod soon too.

Amending to use a rebar script, thanks.

**Comment by wk8** [comment]
@waisbrot : updated; thanks :)

**Comment by waisbrot** [comment]
Looks great!

**Pull request merged**
