### PR TITLE
Adding support for events

### PR DESCRIPTION
**Pull request by wk8**
- `dogstatsd:send` shouldn't be a public function
- added some unit tests on `dogstatsd_worker`
- these unit tests uncovered a bug when reporting float metric values;
  now casting values and intervals to floats

### CODE REVIEW

**Comment by wk8** [comment]
@waisbrot : minor change to the API: `dogstatsd:send` is now private, since I think it has no business being called from outside the module. Are you okay with that? What was the idea of making it public initially?

**Comment by waisbrot** [comment]
Thanks for starting in on the tests! That's definitely something I've been wanting to get filled in.

Support for events: well this is interesting. My intention with `dogstatsd:send/5` was that it _is_ public and that this is analogous to `lager:log` (that is, normally you would call one of the convenience functions, but there's maybe some situation where you want the metric type to be variable). That's probably not terribly important, though; you could always call `dogstatsd:MetricType("some.name", 1)` So I think I'm OK with your suggestion that it be private.

Stylistically, I'd prefer to rename `send/5` to `send_metric/5` and then add a `send_event/5`. These two private functions are where we'd shove the data into a tagged tuple and ship to the worker pool.

**Comment by wk8** [comment]
@waisbrot : updated :)

**Comment by wk8** [comment]
Thanks for merging :)

**Pull request merged**
